package com.fzn.classsign.entity;

public class Token {
    public static String token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIyIiwiYXVkIjpbImNsYXNzU2lnbkFuZHJvaWQiXSwidXNlcl9uYW1lIjoiMiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE1OTI5NDU4NTQsImF1dGhvcml0aWVzIjpbImNvbW1vbiJdLCJqdGkiOiJkYTZlMzIyNS1lYWVlLTRiNTAtODZjNC03YjUyNmYwZmUzNzEiLCJjbGllbnRfaWQiOiJjbGFzc1NpZ25BbmRyb2lkIn0.w4wytYDdKALhnkgpm26L6bKu_puFEKsqrCYU4TTLWwI";


}
